// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoadOfDreams.Data;

#nullable disable

namespace RoadOfDreams.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240107212314_thirdmigration")]
    partial class thirdmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RoadOfDreams.Model.Passagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_passagens");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("agencia");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destino");

                    b.Property<string>("Ida")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("data_ida");

                    b.Property<string>("Lugares")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("quantidade_lugares");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("origem");

                    b.Property<string>("Volta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("data_volta");

                    b.HasKey("Id");

                    b.ToTable("Passagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agencia = "GOL",
                            Destino = "Rio de Janeiro",
                            Ida = "27/07/2022",
                            Lugares = "2",
                            Origem = "São Paulo",
                            Volta = "27/07/2023"
                        },
                        new
                        {
                            Id = 2,
                            Agencia = "AZUL",
                            Destino = "Miami",
                            Ida = "09/09/2021",
                            Lugares = "1",
                            Origem = "São Paulo",
                            Volta = "01/01/2024"
                        },
                        new
                        {
                            Id = 3,
                            Agencia = "EMIRATES",
                            Destino = "Congo",
                            Ida = "27/07/2022",
                            Lugares = "4",
                            Origem = "São Paulo",
                            Volta = "27/08/2022"
                        },
                        new
                        {
                            Id = 4,
                            Agencia = "GOL",
                            Destino = "Emirados Árabes",
                            Ida = "08/10/2019",
                            Lugares = "2",
                            Origem = "Rio de janeiro",
                            Volta = "10/11/2025"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
